# Use root/example as user/password credentials
version: '3.1'

services:

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: db_example
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
          - 3306:3306

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

#    java:
#        image: java-app-img
#        container_name: java-app-cont
#        ports:
#          - 8080:8080
